apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-config
  namespace: microservices
data:
  SPRING_PROFILES_ACTIVE: native
  SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: /config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: microservices
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: bluewhale007/configserver:latest
        resources:
          limits:
            memory: "700Mi"
          requests:
            memory: "500Mi"
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: config-server-config
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS
          valueFrom:
            configMapKeyRef:
              name: config-server-config
              key: SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: rabbitmq-username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: rabbitmq-password
        - name: RABBITMQ_VHOST
          value: "/"
        volumeMounts:
        - name: config-volume
          mountPath: /config
        ports:
        - containerPort: 8888
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: config-volume
        hostPath:
          path: /home/vagrant/macbook-microservices-course/configserver/src/main/resources/config
---
apiVolume: v1
kind: Service
metadata:
  name: config-server
  namespace: microservices
spec:
  selector:
    app: config-server
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  type: ClusterIP